# Tests using RD53 and FPGA co-simulation
test:software:
    variables:
      # Otherwise lock file of cancelled runs might stall future check outs
      # https://gitlab.cern.ch/silab/bdaq53/issues/293
      GIT_STRATEGY: clone
    tags:  # tags to differentiate runners able to run the job
      - docker  # Use CERN shared runners
    image: continuumio/miniconda3:latest  # Ubuntu based miniconda image
    
    before_script:
      - apt-get update --fix-missing
      - apt-get install -y curl
      - su -
      #Install sudo by running:
      - apt-get install sudo -y
      - sudo apt-get install  -y autoconf
      # Installing Required Packages
      - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH=$HOME/miniconda/bin:$PATH
      - conda update --yes conda
      - conda install --yes python=3.7 bitarray contextlib2 cython ipython matplotlib mock nose numba numpy pyqt pyserial pytables pyyaml pyzmq qtpy scipy
      - conda install -c bioconda aenum
      - conda install -c bioconda/label/cf201901 aenum
      - pip install lxml tqdm kafe seaborn aenum verboselogs qtawesome coloredlogs termcolor progressbar-latest pyvisa pyvisa-py pyqtgraph
    # Installing CAN packages
      #Installing SocketCAN devices
      #Installing python-can package
      - pip install python-can
      #Installing libsocketcan package
      - git clone https://git.pengutronix.de/git/tools/libsocketcan
      - cd libsocketcan
      - sudo ./autogen.sh
      - sudo ./configure
      - sudo  make CFLAGS='-fPIC'# to compile the package
      - sudo make install #to install the programs and any data files
      #Installing SocketCAN can-utils
      - sudo apt-get  install can-utils
     # Installing AnaGate CAN interface
      - pip install packages/anagate-0.1.0-py3-none-any.whl
    script:
      - python CANMOPS_test.py
      - python CANMOPS_GUI.py
      # Try to activate conda evironment in the newest broken miniconda docker
      - conda init bash  # https://github.com/ContinuumIO/docker-images/issues/89
      - source ~/.bashrc  # since ==> For changes to take effect, close and re-open your current shell. <==
      - conda activate  # to link properly to pytest

