# Tests using RD53 and FPGA co-simulation
test:canmops:
    variables:
        # Otherwise lock file of cancelled runs might stall future check outs
        GIT_STRATEGY: clone
    tags:  # tags to differentiate runners able to run the job
      - canmops
    before_script:
      # Install miniconda python with required binary packages
      - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH=$HOME/miniconda/bin:$PATH
      - conda update --yes conda
      - conda install --yes conda install python=3.7 bitarray contextlib2 cython ipython matplotlib mock nose numba numpy pyqt pyserial pytables pyyaml pyzmq qtpy scipy
      - conda install --yes pywin32
      - conda install -c bioconda aenum
      - conda install -c bioconda/label/cf201901 aenum
      - pip install lxml tqdm kafe seaborn aenum verboselogs qtawesome coloredlogs termcolor progressbar-latest pyvisa pyvisa-py pyqtgraph

    script:
      - python CANMOPS_test.py
      - python CANMOPS_GUI.py

