# Tests using RD53 and FPGA co-simulation
test:software:
    variables:
      # Otherwise lock file of cancelled runs might stall future check outs
      # https://gitlab.cern.ch/silab/bdaq53/issues/293
      GIT_STRATEGY: clone
    tags:  # tags to differentiate runners able to run the job
      - docker  # Use CERN shared runners
    image: continuumio/miniconda3:latest  # Ubuntu based miniconda image
    
    before_script:
      - apt-get update --fix-missing
      - apt-get install -y curl
      # Install miniconda python with required binary packages
      - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
      - bash miniconda.sh -b -p $HOME/miniconda
      - --yes
      - export PATH=$HOME/miniconda/bin:$PATH
      - conda update --yes conda
      - conda install --yes conda install python=3.7 bitarray contextlib2 cython ipython matplotlib mock nose numba numpy pyqt pyserial pytables pyyaml pyzmq qtpy scipy
      - conda install --yes pywin32
      - conda install -c bioconda aenum
      - conda install -c bioconda/label/cf201901 aenum
      - pip install lxml tqdm kafe seaborn aenum verboselogs qtawesome coloredlogs termcolor progressbar-latest pyvisa pyvisa-py pyqtgraph

    script:
      - python CANMOPS_test.py
      - python CANMOPS_GUI.py
      # Try to activate conda evironment in the newest broken miniconda docker
      - conda init bash  # https://github.com/ContinuumIO/docker-images/issues/89
      - source ~/.bashrc  # since ==> For changes to take effect, close and re-open your current shell. <==
      - conda activate  # to link properly to pytest

