CAN_settings:
        nodeIds: [8]
default_values:
    interface_items: ["----","AnaGate" , "Kvaser","Others"]
    index_items:    ["0x1000"]        

CAN_Interface:
    AnaGate :
        name        :   'AnaGate'
        bitrate     :   125000
        ipAddress   :   '192.168.1.254'
        timeout     :   500
        channel     :   0
    
    Kvaser  :
        name        :   'Kvaser'
        bitrate     :   125000
        ipAddress   :   '192.168.1.254'
        timeout     :   500
        channel     :   0
Other:
    user    :   "Ahmed Qamesh"