Application: 
        device_name             :   'MoPs'
        device_version          :   "v1.0"
        icon_dir                :   "graphics_Utils/icons/icon_mops.png"
        nodeIds                 :   [8]
        index_items             :   ["0x1000", "0x1001","0x1005","0x1014","0x1018","0x1200","0x1800","0x1801","0x1A00","0x1A01","0X2000","0X2001","0X2100"]
        subindex_items          :   ["0","1","2","3","4","5","6"]
        description_items       :   ["<html><b> Device type</b> [Default 191(hex)]</html>",
                                   "<html><b> Error register</b> [Default 0]</html>",
                                   "<html><b> COB-ID SYNC</b> [Default 80(hex)]</html>",
                                   "<html><b> COB-ID EMCY</b> [Default 80(hex)+NodeId]</html>",
                                   "<html><p><b> Identity object needs</b><br><u>subindex 0:</u> Number of entries [Default 1]<br><u>subindex 1:</u> Vendor Id [Default 12345678(hex)+NodeId]</p></html>",
                                   "<html><b> Server SDO parameter 0</b> <br><u>subindex 0:Number of entries [Default 2]</u><br><u>subindex 1:COB-ID client to server [Default 600 (hex) + NodeId]</u><br><u>subindex 2:COB-ID server to client [Default 580 (hex) + NodeId]</u></html>",
                                   "<html><b> TPDO communication parameter 0 </b>]<br><u>subindex 0:</u> Number of entries [Default 6]<br><u>subindex 1:</u> COB-ID [Default 180 (hex) + NodeId]<br><u>subindex 2:</u>Transmission type[Default FE (hex)]<br><u>subindex 3:</u> Inhibit time [Default 0]<br><u>subindex 4:</u> Reserved[Unused]<br><u>subindex 5:</u> Event timer [Default 0]<br><u>subindex 6:</u> SYNC start value[Default 0]</html>"]
                                