CAN_Interfaces: socketcan
channel0:
  bitrate: 125000
  channel: '0'
  samplePoint: 0.5
  SJW: 4
  tseg1: 0
  tseg2: 0
  ipAddress: None
  timeout: 500

channel1:
  bitrate: 125000
  channel: '1'
  samplePoint: 0.5
  SJW: 4
  tseg1: 0
  tseg2: 0
  ipAddress: None
  timeout: 500