CAN_Interfaces: socketcan
channel0:
  bitrate: 125000
  channel: 0
  samplePoint: 0.5
  SJW: 4
  tseg1: 7
  tseg2: 8
  ipAddress: None
  timeout: 500
channel1:
  bitrate: 125000
  channel: 1
  samplePoint: 0.5
  SJW: 4
  tseg1: 7
  tseg2: 8
  ipAddress: None
  timeout: 500
